mangaki/mangaki/urls.py
from django.contrib.auth.decorators import login_required
from django.conf.urls import patterns, include, url
from django.contrib import admin
from discourse import views as discourse_views
from mangaki import views

urlpatterns = [
    # Examples:
    # url(r'^$', views.home, name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^$', views.index),
    url(r'^data/(?P<category>\w+)\.json$', views.get_works),
    url(r'^data/anime/(?P<query>.+)\.json$', views.get_extra_anime),
    url(r'^data/manga/(?P<query>.+)\.json$', views.get_extra_manga),
    url(r'^data/reco/(?P<category>\w+)/(?P<editor>\w+)\.json$', views.get_reco_list),
    url(r'^data/card/(?P<category>\w+)/(?P<sort_id>\d+)\.json$', views.get_card),
    url(r'^getuser/(?P<work_id>\w+)\.json$', views.get_user_for_recommendations),
    url(r'^getuser\.json$', views.get_users),
    url(r'^recommend/(?P<work_id>\w+)/(?P<target_id>\w+)$', views.recommend_work),
    url(r'^removeReco/(?P<work_id>\d+)/(?P<username>\w+)/(?P<targetname>\w+)$', views.remove_reco),
    url(r'^removeReco/(?P<targetname>\w+)$', views.remove_all_reco),
    url(r'^users/', views.UserList.as_view()),
    url(r'^user/', include('allauth.urls')),
    url(r'^u/(?P<username>.+)$', views.get_profile),  # login_required?
    url(r'^reco/$', views.get_reco),
    url(r'^anime/$', views.AnimeList.as_view()),
    url(r'^anime/(?P<pk>\d+)$', views.AnimeDetail.as_view(), name='anime-detail'),
    url(r'^anime/(?P<pk>\d+)/nsfw$', views.report_nsfw),
    url(r'^artist/(?P<artist_id>\d+)$', views.AnimeList.as_view()),
    url(r'^artist/(?P<artist_id>\d+)/add/(?P<work_id>\d+)$', views.add_pairing),
    url(r'^manga/$', views.MangaList.as_view()),
    url(r'^manga/(?P<pk>\d+)$', views.MangaDetail.as_view()),
    url(r'^anime/(?P<pk>\d+)/nsfw$', views.report_nsfw),
    url(r'^work/(?P<work_id>\d+)$', views.rate_work),
    url(r'^shared/$', views.update_shared),
    url(r'^nsfw/$', views.update_nsfw),
    url(r'^newsletter/$', views.update_newsletter),
    url(r'^reco_willsee/$', views.update_reco_willsee),
    url(r'^mal/(?P<mal_username>.+)$', views.import_from_mal),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^discourse/sso$', discourse_views.sso),
    url(r'^about/$', views.about),
    url(r'^events/$', views.events),
    url(r'^unsubscribe/(?P<pk>\d+)/(?P<key>\w+)$', views.unsubscribe),
    # url(r'^lookup/$', views.lookup_work'),
    url(r'^(?P<slug>[\w-]+)/$', views.MarkdownView.as_view()),
    url(r'^top/(?P<category_slug>[\w-]+)/$', views.top),
]

mangaki/irl/models.py
from django.db import models
from mangaki.models import Anime
import locale


class Location(models.Model):
    title = models.CharField(max_length=64, verbose_name='Titre')
    address = models.TextField(verbose_name='Adresse')
    postal_code = models.CharField(max_length=5, verbose_name='Code postal')
    city = models.CharField(max_length=64, verbose_name='Ville')

    def __str__(self):
        return '%s, %s' % (self.title, self.city)


class Event(models.Model):
    anime = models.ForeignKey(Anime)
    location = models.ForeignKey('Location', blank=True, null=True)
    event_type = models.CharField(max_length=9, choices=(
        ('premiere', 'avant-première'),
        ('screening', 'projection'),
        ('release', 'sortie'),
        ('tv', 'diffusion')
    ))
    language = models.CharField(max_length=6, choices=(
        ('vf', 'VF'),
        ('vostfr', 'VOSTFR'),
        ('vosta', 'VOSTA'),
    ))
    channel = models.CharField(max_length=16, blank=True, default='')
    date = models.DateTimeField()
    link = models.URLField(blank=True, default='')

    def __str__(self):
        return '%s %s' % (self.event_type, self.anime.title)

    def get_date(self):
        locale.setlocale(locale.LC_ALL, 'fr_FR.UTF-8')
        return self.date.strftime('%A %-d %B %Y à %H h %M').lower()

    def to_html(self):
        common = '{type} <em>{title}</em> le <strong>{date}</strong>'.format(
            type=self.get_event_type_display(),
            title=self.anime.title,
            date=self.get_date())
        if self.event_type == 'tv':
            return common + ' sur ' + self.channel

        if self.location:
            if self.link:
                link_tpl = ', <a href="{url}" target="_blank">{location}</a>'
                return common + link_tpl.format(
                    url=self.link, location=self.location)
            else:
                return common + ', ' + self.location

        return common

    class Meta:
        ordering = ['date']


class Partner(models.Model):
    name = models.CharField(max_length=32)
    url = models.CharField(max_length=512)
    image = models.CharField(max_length=32, verbose_name="Fichier logo")

    class Meta:
        ordering = ['name'] 

mangaki/mangaki/forms.py
from django.forms import ModelForm, HiddenInput
from mangaki.models import Suggestion


class SuggestionForm(ModelForm):
    class Meta:
        model = Suggestion
        fields = ['work', 'problem', 'message']
        widgets = {'work': HiddenInput()}

mangaki/mangaki/views.py
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.views.generic.edit import FormMixin
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseForbidden, Http404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.utils import timezone
from django.utils.timezone import utc

from django.dispatch import receiver
from django.db.models import Count
from django.db import connection
from allauth.account.signals import user_signed_up
from allauth.socialaccount.signals import social_account_added
from mangaki.models import Work, Anime, Manga, Rating, Page, Profile, Artist, Suggestion, SearchIssue, Announcement, Recommendation, Pairing, Deck, Top, Ranking
from mangaki.mixins import AjaxableResponseMixin
from mangaki.forms import SuggestionForm
from mangaki.utils.mal import lookup_mal_api, import_mal, retrieve_anime
from mangaki.utils.recommendations import get_recommendations
from mangaki.utils.chrono import Chrono
from irl.models import Event, Partner

from collections import Counter
from markdown import markdown
from urllib.parse import urlencode
from itertools import groupby
from random import shuffle, randint
from secret import HASH_PADDLE
import datetime
import hashlib
import json

from mangaki.choices import TOP_CATEGORY_CHOICES

POSTERS_PER_PAGE = 24
TITLES_PER_PAGE = 24
USERNAMES_PER_PAGE = 24
REFERENCE_DOMAINS = (
    ('http://myanimelist.net', 'myAnimeList'),
    ('http://animeka.com', 'Animeka'),
    ('http://vgmdb.net', 'VGMdb'),
    ('http://anidb.net', 'AniDB')
)

RATING_COLORS = {
    'favorite': {'normal': '#f8d549', 'highlight': '#f8d549'},
    'like': {'normal': '#5cb85c', 'highlight': '#47a447'},
    'neutral': {'normal': '#f0ad4e', 'highlight': '#ec971f'},
    'dislike': {'normal': '#d9534f', 'highlight': '#c9302c'},
    'willsee': {'normal': '#337ab7', 'highlight': '#286090'},
    'wontsee': {'normal': '#5bc0de', 'highlight': '#31b0d5'}
}


def display_queries():
    for line in connection.queries:
        print(line['sql'][:100], line['time'])


def get_rated_works(user):
    rated_works = {}
    for work_id, choice in Rating.objects.filter(user=user).values_list('work_id', 'choice'):
        rated_works[work_id] = choice
    print(len(rated_works))
    return rated_works


def update_poster_if_nsfw(obj, user):
    if obj.nsfw and (not user.is_authenticated() or not user.profile.nsfw_ok):
        obj.poster = '/static/img/nsfw.jpg'  # NSFW


def update_poster_if_nsfw_dict(d, user):
    if d['nsfw'] and (not user.is_authenticated() or not user.profile.nsfw_ok):
        d['poster'] = '/static/img/nsfw.jpg'  # NSFW


def update_score_while_rating(user, work, choice):
    recommendations_list = Recommendation.objects.filter(target_user=user, work=work)
    for reco in recommendations_list:
        if choice == 'like':
            reco.user.profile.score += 1
        elif choice == 'favorite':
            reco.user.profile.score += 5
        if Rating.objects.filter(user=user, work=work, choice='like').count() > 0:
            reco.user.profile.score -= 1
        if Rating.objects.filter(user=user, work=work, choice='favorite').count() > 0:
            reco.user.profile.score -= 5
        Profile.objects.filter(user=reco.user).update(score=reco.user.profile.score)


def update_score_while_unrating(user, work, choice):
    recommendations_list = Recommendation.objects.filter(target_user=user, work=work)
    for reco in recommendations_list:
        if choice == 'like':
            reco.user.profile.score -= 1
            Profile.objects.filter(user=reco.user).update(score=reco.user.profile.score)
        elif choice == 'favorite':
            reco.user.profile.score -= 5
            Profile.objects.filter(user=reco.user).update(score=reco.user.profile.score)


class AnimeDetail(AjaxableResponseMixin, FormMixin, DetailView):
    queryset = Anime.objects.select_related('director', 'composer', 'author')
    form_class = SuggestionForm

    def get_success_url(self):
        return 'anime/%d' % self.object.pk

    def get_context_data(self, **kwargs):
        context = super(AnimeDetail, self).get_context_data(**kwargs)
        anime = self.object
        update_poster_if_nsfw(anime, self.request.user)
        context['object'].source = anime.source.split(',')[0]

        genres = []
        for genre in anime.genre.all():
            genres.append(genre.title)
        context['genres'] = ', '.join(genres)

        if self.request.user.is_authenticated():
            context['suggestion_form'] = SuggestionForm(instance=Suggestion(user=self.request.user, work=self.object))
            try:
                if Rating.objects.filter(user=self.request.user, work=anime, choice='favorite').count() > 0:
                    context['rating'] = 'favorite'
                else:
                    context['rating'] = anime.rating_set.get(user=self.request.user).choice
            except Rating.DoesNotExist:
                pass

        context['references'] = []
        for reference in anime.reference_set.all():
            for domain, name in REFERENCE_DOMAINS:
                if reference.url.startswith(domain):
                    context['references'].append((reference.url, name))

        nb = Counter(Rating.objects.filter(work=anime).values_list('choice', flat=True))
        labels = {'favorite': 'Ajoutés aux favoris', 'like': 'Ont aimé', 'neutral': 'Neutre', 'dislike': 'N\'ont pas aimé', 'willsee': 'Ont envie de voir', 'wontsee': 'N\'ont pas envie de voir'}
        context['stats'] = []
        seen_ratings = ['favorite', 'like', 'neutral', 'dislike']
        for rating in seen_ratings:
            context['stats'].append({'value': nb[rating], 'colors': RATING_COLORS[rating], 'label': labels[rating]})
        total = sum(nb.values())
        if total > 0:
            seen_total = sum(nb[rating] for rating in seen_ratings)
            context['seen_percent'] = round(100 * seen_total / float(total))
        return context

    def post(self, request, *args, **kwargs):
        if not request.user.is_authenticated():
            return HttpResponseForbidden()
        self.object = self.get_object()
        form_class = self.get_form_class()
        form = self.get_form(form_class)

        if form.is_valid():
            return self.form_valid(form)
        return self.form_invalid(form)

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.save()
        return super(AnimeDetail, self).form_valid(form)


class MangaDetail(AjaxableResponseMixin, FormMixin, DetailView):
    model = Manga
    form_class = SuggestionForm

    def get_success_url(self):
        return 'manga/%d' % self.object.pk

    def get_context_data(self, **kwargs):
        context = super(MangaDetail, self).get_context_data(**kwargs)
        update_poster_if_nsfw(self.object, self.request.user)
        print(self.object.poster)
        context['object'].source = context['object'].source.split(',')[0]

        genres = []
        for genre in context['object'].genre.all():
            genres.append(genre.title)
        context['genres'] = ', '.join(genres)

        if self.request.user.is_authenticated():
            context['suggestion_form'] = SuggestionForm(instance=Suggestion(user=self.request.user, work=self.object))
            try:
                if Rating.objects.filter(user=self.request.user, work=self.object, choice='favorite').count() > 0:
                    context['rating'] = 'favorite'
                else:
                    context['rating'] = self.object.rating_set.get(user=self.request.user).choice
            except Rating.DoesNotExist:
                pass
        return context

    def post(self, request, *args, **kwargs):
        if not request.user.is_authenticated():
            return HttpResponseForbidden()
        self.object = self.get_object()
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        if form.is_valid():
            return self.form_valid(form)
        return self.form_invalid(form)

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.save()
        return super(MangaDetail, self).form_valid(form)


def controversy(nb_likes, nb_dislikes):
    if nb_likes == 0 or nb_dislikes == 0:
        return 0
    return (nb_likes + nb_dislikes) ** min(float(nb_likes) / nb_dislikes, float(nb_dislikes) / nb_likes)


def get_scores(bundle, ranking='controversy'):
    ratings = Rating.objects.filter(work__in=bundle).values('work', 'choice').annotate(count=Count('pk')).order_by('work', 'choice')
    score = {}
    for work_id, ratings in groupby(ratings, lambda rating: rating['work']):
        nb_likes = nb_dislikes = 0
        for rating in ratings:
            if rating['choice'] == 'like':
                nb_likes = rating['count']
            elif rating['choice'] == 'dislike':
                nb_dislikes = rating['count']
        if ranking == 'controversy':
            score[work_id] = controversy(nb_likes, nb_dislikes)
        elif ranking == 'top':
            score[work_id] = nb_likes if nb_dislikes <= 20 else 0
        elif ranking == 'random':  # Perles au hasard
            score[work_id] = randint(1, 42) if nb_dislikes <= 5 and nb_likes >= 3 else 0
    return score


def get_bundle(category, sort_mode, my_rated_works={}):
    already_rated = ', '.join(map(str, my_rated_works.keys())) if my_rated_works.keys() else '0'

mangaki/mangaki/templates/mangaki/anime_detail.html
{% extends "base.html" %}
{% load bootstrap %}

{% block opengraph %}
<meta property="og:title" content="{{ object.title }} - Mangaki" />
<meta property="og:type" content="video.movie" />
<meta property="og:url" content="http://mangaki.fr{% url "anime-detail" object.id %}" />
{% if object.poster %}
  <meta property="og:image" content="{{ object.poster }}" />
{% endif %}
{% if object.synopsis %}
  <meta property="og:description" content="{{ object.synopsis }}" />
  <meta name="description" content="{{ object.synopsis }}" />
{% endif %}
{% endblock %}

{% block title %}{{ object.title }} - Mangaki{% endblock %}

{% block body %}
<div class="alert alert-warning" role="alert" id="sorry" style="display: none"></div>
<div class="row">
    <div class="col-md-12"> <!--  col-md-push-3 -->
        {% if anime.event_set.all.count %}
        <div class="well">
          Cet anime est prévu pour les événements suivants :
          <ul>
          {% for event in anime.event_set.all %}
            <li>{{ event.to_html|safe }}</li>
          {% endfor %}
          </ul>
        </div>
        {% endif %}
        <h1>{{ object.title }}</h1>
    </div>
    <div class="col-sm-6 col-md-4 manga-sheet"> <!-- fluid col-sm-6 col-md-pull-3 -->
        <div class="work-sheet data" data-category="anime" data-id="{{ object.id }}">
            {% include "work_rating.html" with category="anime" work=object show_title=False %}
        </div>
    </div>
    <div class="col-sm-6 col-md-3">
        <p>Nombre d'épisodes : {{ object.nb_episodes }}</p>

        <p>Réalisateur : <a href="/artist/{{ object.director.id }}">{{ object.director }}</a></p>
        <p>Compositeur : <a href="/artist/{{ object.composer.id }}">{{ object.composer }}</a></p>
        <p>Auteur : <a href="/artist/{{ object.author.id }}">{{ object.author }}</a></p>
        <p>Éditeur : {{ object.editor }}</p>
        <p>Origine : {{ object.origin }}</p>
        <p>Genres : {{ genres }}</p>
        <p>Type : {{ object.anime_type }}</p>
    </div>
    <div class="col-sm-6 col-md-5">
        <h3>Statistiques{% if seen_percent %} <small>(vu par {{ seen_percent }}&nbsp;% des membres qui l'ont noté)</small>{% endif %}</h3>
        <div style="max-width: 420px; max-height: 200px">
          <canvas id="stats" />
        </div>
        {% if references %}
          <h3>Références</h3>
          <ul>
          {% for url, name in references %}
              <li><a href="{{ url }}" target="_blank">Voir sur {{ name }}</a></li>
          {% endfor %}
          </ul>
        {% endif %}
    </div>
</div>
<br />
{% if object.synopsis %}
    <div class="well">{{ object.synopsis|safe }}</div>
{% endif %}
{% if user.is_authenticated %}
<a href="http://meta.mangaki.fr/session/sso" target="_blank"><button type="button" class="btn btn-primary">En discuter sur le forum</button></a>
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#suggestionModal">Proposer une modification</button>

<form class="typeahead-demo {{ user.username }}">
    <input type="text" data-username="{{ user.username }}" class="typeahead" placeholder="Conseiller cet anime à un utilisateur" />
</form>
<div class="alert alert-danger" role="alert" id="alert-reco" style="display: none">Cet utilisateur a déjà vu l'anime que vous voulez lui recommander</div>
<div class="alert alert-success" role="alert" id="success-reco" style="display: none">La recommandation a bien été effectuée</div>

<div class="modal fade" id="suggestionModal" tabindex="-1" role="dialog" aria-labelledby="suggestionModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="suggestionModalLabel">Proposer une amélioration pour {{ object.title }}</h4>
      </div>
      <h5 style="text-indent:2em">Bienvenue sur l’interface d’amélioration de Mangaki :</h5>
      <ol>
      <li>Indiquez quelle partie de la fiche est concernée par votre proposition</li>
      <li>Écrivez-nous votre idée/solution, et envoyez !</li>
      </ol>
      <form id="suggestion" action="/anime/{{ object.id }}" method="POST">
      {% csrf_token %}
      <div class="modal-body">
        <div class="alert alert-danger" role="alert" id="alert" style="display: none"></div>
        <div class="alert alert-success" role="alert" id="success" style="display: none"></div>
        {{ suggestion_form|bootstrap }}
      </div>
      </form>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Fermer</button>
        <button type="button" class="btn btn-primary" onclick="suggestion('anime')">Envoyer</button>
      </div>
    </div>
  </div>
</div>
{% endif %}

<script>
category='anime';
work_id='{{ object.id }}';
loadMenuReco();
doughnutData = [
  {% for stat in stats %}
    {value: {{ stat.value }}, color: '{{ stat.colors.normal }}', highlight: '{{ stat.colors.highlight }}', label: "{{ stat.label|safe }}"},
  {% endfor %}
]
window.onload = function(){
  var ctx = document.getElementById("stats").getContext("2d");
  window.myDoughnut = new Chart(ctx).Doughnut(doughnutData, {responsive: true});
};
</script>
{% endblock %}

mangaki/mangaki/templates/mangaki/anime_list.html
{% extends "base.html" %}

{% block body %}
{% if not artist %}
  {% if user.is_authenticated %}
  <div class="row">
      <div class="col-md-12 col-sm-12">
          <div class="well">
            <p>
              Notez quelques <em>anime</em>, via les listes ci-dessous ou la barre de recherche.<br />
              Puis cliquez sur <a href="/reco/?category=anime">Recommandations</a> pour voir ce que vous conseille <em>Mangaki</em> !
            </p>
          </div>
      </div>
      <div class="row">
          <div class="col-md-2 col-sm-12"></div>
          <div class="col-md-8 col-sm-12">
              <div class="margin10top">
                  <p style="text-align: center">Légende :
                  <span class="label label-favorite"><span class="glyphicon glyphicon-star"></span> Mettre en favori</span>
                  <span class="label label-success"><span class="glyphicon glyphicon-thumbs-up"></span> J'aime</span>
                  <span class="label label-warning"><span class="glyphicon glyphicon-adjust"></span> Neutre</span>
                  <span class="label label-danger"><span class="glyphicon glyphicon-thumbs-down"></span> Je n'aime pas</span>
                  <span class="label label-primary"><span class="glyphicon glyphicon-eye-open"></span> Je veux voir</span>
                  <span class="label label-info"><span class="glyphicon glyphicon-eye-close"></span> Je ne veux pas voir</span></p>
                  <form class="typeahead-demo {{ category }}">
                      <input type="text" data-category="{{ category }}" class="typeahead" placeholder="Entrez un titre d'anime (actuellement {{ anime_count }})…" />
                  </form>
              </div>
          </div>
          <div class="col-md-2 col-sm-12"></div>
      </div>
  </div>
  {% else %}
  <div class=" col-md-12 col-sm-12">
    <p class="well">
      Nouveau sur Mangaki ? <a href="/user/signup/?next={{ request.get_full_path|urlencode }}">Inscrivez-vous</a> puis
      <a href="/user/login/?next={{ request.get_full_path|urlencode }}">connectez-vous</a> pour noter ces <em>anime</em>
      et obtenir des recommandations.
    </p>
  </div>
  {% endif %}
{% endif %}

{% if artist %}
  <h1>{{ artist }}</h1>
  <hr />
{% else %}
  <b>
  <div class="collapse navbar-collapse" id="menu-collapse">
     <ul class="nav navbar-nav">
  {% for letter in "#ABCDEFGHIJKLMNOPQRSTUVWXYZ" %}
       <li class="dropdown">
       <a href="?sort=alpha&amp;letter={{ letter|lower }}">
           {{letter}}
       </a>
       </li>
  {% endfor %}
     </ul>
  </div>
  </b>

  <div class="alert alert-warning" role="alert" id="sorry" style="display: none"></div>
  <div class="row">
      <div class=" margin col-md-12 col-sm-12">
          <ul class="nav nav-tabs">
              <li role="presentation"{% if params.sort == 'mosaic' %} class="active"{% endif %}><a href="/anime/">Mosaïque</a></li>
              <li role="presentation"{% if params.sort == 'popularity' %} class="active"{% endif %}><a href="/anime/?sort=popularity">Les plus populaires</a></li>
              <li role="presentation"{% if params.sort == 'controversy' %} class="active"{% endif %}><a href="/anime/?sort=controversy">Les plus controversés</a></li>
              <li role="presentation"{% if params.sort == 'top' %} class="active"{% endif %}><a href="/anime/?sort=top">Les plus aimés</a></li>
              <li role="presentation"{% if params.sort == 'random' %} class="active"{% endif %}><a href="/anime/?sort=random">Perles au hasard</a></li>
          </ul>
      </div>
  </div>
  <br />
{% endif %}

<div class="row works-list">
    {% for object in object_list %}
        {% include template_mode with work=object category="anime" rating=object.rating %}
    {% endfor %}
</div>

{% if user.is_authenticated %}
  {% if artist %}
    Signaler une œuvre manquante pour {{ artist }} ?
    <form class="typeahead-demo {{ category }}">
        <input type="text" data-category="{{ category }}" class="typeahead" placeholder="Entrez un titre d'anime (actuellement {{ anime_count }})…" />
    </form>
  {% else %}
    <div class="row margin">
        <div class="margin col-md-12 col-sm-12">
            <a class="btn btn-primary btn-lg" href="/reco/?category=anime" style="display: block; margin: auto">Je n'arrive plus à noter, conseillez-moi !</a>
        </div>
    </div>
  {% endif %}
{% endif %}

{% if params.sort != 'mosaic' %}
<nav style="text-align: center">
  <ul class="pagination">
    {% if object_list.has_previous %}
    <li>
      <a href="?{{ url }}&amp;page={{ object_list.previous_page_number }}" aria-label="Previous">
        <span aria-hidden="true">&laquo;</span>
      </a>
    </li>
    {% endif %}
    {% for page in pages %}
        <li><a href="?{{ url }}&amp;page={{ page }}">{% if params.page == page %}<strong>{{ page }}</strong>{% else %}{{ page }}{% endif %}</a></li>
    {% endfor %}
    {% if object_list.has_next %}
    <li>
      <a href="?{{ url }}&amp;page={{ object_list.next_page_number }}" aria-label="Next">
        <span aria-hidden="true">&raquo;</span>
      </a>
    </li>
    {% endif %}
  </ul>
</nav>
{% endif %}
<br />
<br />
<br />
<script>
category = 'anime';
sort_mode = '{{ params.sort }}';
{% if artist %}
artistID = {{ artist.id }};
{% endif %}
loadMenu();
{% if params.sort == 'mosaic' %}
for(pos = 1; pos <= 4; pos++)
    loadCard(pos);
{% endif %}
</script>
{% endblock %}